---
- name: Check if image with the correct name already exists in Glance
  openstack.cloud.image_info:
    name: "{{ gpu_validation_image_name }}"
    ca_cert: "{{ gpu_validation_ca_cert_path }}"
  register: _gpu_validation_image_info

- name: Set fact if image exists
  ansible.builtin.set_fact:
    _gpu_validation_image_exists: "{{ (_gpu_validation_image_info.images | length) > 0 }}"

- name: Download VM image
  ansible.builtin.get_url:
    url: "{{ gpu_validation_image_url }}"
    dest: "/tmp/{{ gpu_validation_image_url | basename }}"
    mode: '0644'
  when: not _gpu_validation_image_exists

- name: Create glance image from GPU validation download source
  openstack.cloud.image:
    name: "{{ gpu_validation_image_name }}"
    container_format: bare
    disk_format: qcow2
    filename: "/tmp/{{ gpu_validation_image_url | basename }}"
    visibility: public
    ca_cert: "{{ gpu_validation_ca_cert_path }}"
  when: not _gpu_validation_image_exists

- name: Create flavor for GPU validation
  openstack.cloud.compute_flavor:
    name: "{{ gpu_validation_flavor_name }}"
    ram: "{{ gpu_validation_flavor_ram }}"
    vcpus: "{{ gpu_validation_flavor_vcpus }}"
    disk: "{{ gpu_validation_flavor_disk }}"
    extra_specs:
      "pci_passthrough:alias": "{{ gpu_validation_pci_alias }}:{{ gpu_validation_flavor_gpus }}"
      "hw:pci_numa_affinity_policy": "preferred"
      "hw:hide_hypervisor_id": "true"
      "hw:kvm_hidden": "true"
      "hw:cpu_model": "host-passthrough"
    ca_cert: "{{ gpu_validation_ca_cert_path }}"
